### PR TITLE
Add Image upload

### PR DESCRIPTION
**Pull request by ChenChiehYu**
Only complete image upload for essay question, needs to figure out how to display them.

### CODE REVIEW

**Review by ChenChiehYu — COMMENTED** [review]
just image upload in essay question, need to find how to display image later

**Comment by ChenChiehYu** [comment]
https://www.geeksforgeeks.org/python-uploading-images-in-django/

**Review by Albert-Alvaro — APPROVED** [review]
code looks ok

**Review by ChenChiehYu — COMMENTED** [review]
testing commit

**Pull request closed without merging**
